name: innosetup
description: Make windows installer for Flutter & vanilla Dart powered apps powered by Inno Setup.
version: 0.1.4
homepage: https://github.com/aswinmurali-io/flutter_innosetup

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  meta: '>=1.9.1'
  version: ^3.0.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
